apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)

    scope "/tasks" do
      get("/create_contract_methods", TaskController, :create_contract_methods, as: :create_contract_methods)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/api_router.ex
defmodule RPCTranslatorForwarder do
  @moduledoc """
  Phoenix router limits forwarding,
  so this module is to forward old paths for backward compatibility
  """
  alias BlockScoutWeb.API.RPC.RPCTranslator
  defdelegate init(opts), to: RPCTranslator
  defdelegate call(conn, opts), to: RPCTranslator
end

defmodule BlockScoutWeb.ApiRouter do
  @moduledoc """
  Router for API
  """
  use BlockScoutWeb, :router

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/v1", BlockScoutWeb.API.V1, as: :api_v1 do
    pipe_through(:api)
    get("/health", HealthController, :health)

    if Application.get_env(:block_scout_web, __MODULE__)[:writing_enabled] do
      post("/decompiled_smart_contract", DecompiledSmartContractController, :create)
      post("/verified_smart_contracts", VerifiedSmartContractController, :create)
    end
  end

  if Application.get_env(:block_scout_web, __MODULE__)[:reading_enabled] do
    scope "/" do
      alias BlockScoutWeb.API.{RPC, V1}
      pipe_through(:api)

      scope "/v1", as: :api_v1 do
        get("/supply", V1.SupplyController, :supply)
        post("/eth_rpc", RPC.EthController, :eth_request)
      end

      # For backward compatibility. Should be removed
      post("/eth_rpc", RPC.EthController, :eth_request)
    end
  end

  scope "/" do
    pipe_through(:api)
    alias BlockScoutWeb.API.RPC

    scope "/v1", as: :api_v1 do
      forward("/", RPC.RPCTranslator, %{
        "block" => {RPC.BlockController, []},
        "account" => {RPC.AddressController, []},
        "logs" => {RPC.LogsController, []},
        "token" => {RPC.TokenController, []},
        "stats" => {RPC.StatsController, []},
        "contract" => {RPC.ContractController, [:verify]},
        "transaction" => {RPC.TransactionController, []}
      })
    end

    # For backward compatibility. Should be removed
    forward("/", RPCTranslatorForwarder, %{
      "block" => {RPC.BlockController, []},
      "account" => {RPC.AddressController, []},
      "logs" => {RPC.LogsController, []},
      "token" => {RPC.TokenController, []},
      "stats" => {RPC.StatsController, []},
      "contract" => {RPC.ContractController, [:verify]},
      "transaction" => {RPC.TransactionController, []}
    })
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.GraphQL
  alias BlockScoutWeb.{ApiRouter, WebRouter}

  forward("/wobserver", Wobserver.Web.Router)
  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  forward("/api", ApiRouter)

  if Application.get_env(:block_scout_web, ApiRouter)[:reading_enabled] do
    # Needs to be 200 to support the schema introspection for graphiql
    @max_complexity 200

    forward("/graphql", Absinthe.Plug,
      schema: BlockScoutWeb.Schema,
      analyze_complexity: true,
      max_complexity: @max_complexity
    )

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: BlockScoutWeb.Schema,
      interface: :advanced,
      default_query: GraphQL.default_query(),
      socket: BlockScoutWeb.UserSocket,
      analyze_complexity: true,
      max_complexity: @max_complexity
    )
  else
    scope "/", BlockScoutWeb do
      pipe_through(:browser)
      get("/api_docs", PageNotFoundController, :index)
      get("/eth_rpc_api_docs", PageNotFoundController, :index)
    end
  end

  scope "/", BlockScoutWeb do
    pipe_through(:browser)

    get("/api_docs", APIDocsController, :index)
    get("/eth_rpc_api_docs", APIDocsController, :eth_rpc)
  end

  scope "/verify_smart_contract" do
    pipe_through(:api)

    post("/contract_verifications", BlockScoutWeb.AddressContractVerificationController, :create)
  end

  if Application.get_env(:block_scout_web, WebRouter)[:enabled] do
    forward("/", BlockScoutWeb.WebRouter)
  else
    scope "/", BlockScoutWeb do
      pipe_through(:browser)

      forward("/", APIDocsController, :index)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/web_router.ex
defmodule BlockScoutWeb.WebRouter do
  @moduledoc """
  Router for web app
  """
  use BlockScoutWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  # Disallows Iframes (write routes)
  scope "/", BlockScoutWeb do
    pipe_through(:browser)
  end

  # Allows Iframes (read-only routes)
  scope "/", BlockScoutWeb do
    pipe_through([:browser, BlockScoutWeb.Plug.AllowIframe])

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources("/market_history_chart", Chain.MarketHistoryChartController,
      only: [:show],
      singleton: true
    )

    resources "/blocks", BlockController, only: [:index, :show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    resources("/pending_transactions", PendingTransactionController, only: [:index])

    resources("/recent_transactions", RecentTransactionsController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal_transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/raw_trace",
        TransactionRawTraceController,
        only: [:index],
        as: :raw_trace
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token_transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal_transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/decompiled_contracts",
        AddressDecompiledContractController,
        only: [:index],
        as: :decompiled_contract
      )

      resources(
        "/logs",
        AddressLogsController,
        only: [:index],
        as: :logs
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new],
        as: :verify_contract
      )

      resources(
        "/read_contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token_transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token_balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )

      resources(
        "/coin_balances",
        AddressCoinBalanceController,
        only: [:index],
        as: :coin_balance
      )

      resources(
        "/coin_balances/by_day",
        AddressCoinBalanceByDayController,
        only: [:index],
        as: :coin_balance_by_day
      )
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token_transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read_contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token_holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )
    end

    resources(
      "/smart_contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/search", ChainController, :search)

    get("/search_logs", AddressLogsController, :search_logs)

    get("/transactions_csv", AddressTransactionController, :transactions_csv)

    get("/token_autocomplete", ChainController, :token_autocomplete)

    get("/token_transfers_csv", AddressTransactionController, :token_transfers_csv)

    get("/chain_blocks", ChainController, :chain_blocks, as: :chain_blocks)

    get("/*path", PageNotFoundController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
defmodule BlockScoutWeb.API.RPC.TransactionController do
  use BlockScoutWeb, :controller

  import BlockScoutWeb.Chain, only: [paging_options: 1, next_page_params: 3, split_list_by_page: 1]

  alias Explorer.Chain

  def gettxinfo(conn, params) do
    with {:txhash_param, {:ok, txhash_param}} <- fetch_txhash(params),
         {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param),
         {:transaction, {:ok, transaction}} <- transaction_from_hash(transaction_hash),
         paging_options <- paging_options(params) do
      logs = Chain.transaction_to_logs(transaction_hash, paging_options)
      {logs, next_page} = split_list_by_page(logs)

      render(conn, :gettxinfo, %{
        transaction: transaction,
        block_height: Chain.block_height(),
        logs: logs,
        next_page_params: next_page_params(next_page, logs, params)
      })
    else
      {:transaction, :error} ->
        render(conn, :error, error: "Transaction not found")

      {:txhash_param, :error} ->
        render(conn, :error, error: "Query parameter txhash is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")
    end
  end

  def gettxreceiptstatus(conn, params) do
    with {:txhash_param, {:ok, txhash_param}} <- fetch_txhash(params),
         {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param) do
      status = to_transaction_status(transaction_hash)
      render(conn, :gettxreceiptstatus, %{status: status})
    else
      {:txhash_param, :error} ->
        render(conn, :error, error: "Query parameter txhash is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")
    end
  end

  def getstatus(conn, params) do
    with {:txhash_param, {:ok, txhash_param}} <- fetch_txhash(params),
         {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param) do
      error = to_transaction_error(transaction_hash)
      render(conn, :getstatus, %{error: error})
    else
      {:txhash_param, :error} ->
        render(conn, :error, error: "Query parameter txhash is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")
    end
  end

  defp fetch_txhash(params) do
    {:txhash_param, Map.fetch(params, "txhash")}
  end

  defp transaction_from_hash(transaction_hash) do
    case Chain.hash_to_transaction(transaction_hash, necessity_by_association: %{block: :required}) do
      {:error, :not_found} -> {:transaction, :error}
      {:ok, transaction} -> {:transaction, {:ok, transaction}}
    end
  end

  defp to_transaction_hash(transaction_hash_string) do
    {:format, Chain.string_to_transaction_hash(transaction_hash_string)}
  end

  defp to_transaction_status(transaction_hash) do
    case Chain.hash_to_transaction(transaction_hash) do
      {:error, :not_found} -> ""
      {:ok, transaction} -> transaction.status
    end
  end

  defp to_transaction_error(transaction_hash) do
    with {:ok, transaction} <- Chain.hash_to_transaction(transaction_hash),
         {:error, error} <- Chain.transaction_to_status(transaction) do
      error
    else
      _ -> ""
    end
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
defmodule BlockScoutWeb.TransactionController do
  use BlockScoutWeb, :controller

  import BlockScoutWeb.Chain, only: [paging_options: 1, next_page_params: 3, split_list_by_page: 1]

  alias BlockScoutWeb.TransactionView
  alias Explorer.Chain
  alias Phoenix.View

  def index(conn, %{"type" => "JSON"} = params) do
    full_options =
      Keyword.merge(
        [
          necessity_by_association: %{
            :block => :required,
            [created_contract_address: :names] => :optional,
            [from_address: :names] => :optional,
            [to_address: :names] => :optional
          }
        ],
        paging_options(params)
      )

    transactions_plus_one = Chain.recent_collated_transactions(full_options)
    {transactions, next_page} = split_list_by_page(transactions_plus_one)

    next_page_path =
      case next_page_params(next_page, transactions, params) do
        nil ->
          nil

        next_page_params ->
          transaction_path(conn, :index, Map.delete(next_page_params, "type"))
      end

    json(
      conn,
      %{
        items:
          Enum.map(transactions, fn transaction ->
            View.render_to_string(
              TransactionView,
              "_tile.html",
              transaction: transaction
            )
          end),
        next_page_path: next_page_path
      }
    )
  end

  def index(conn, _params) do
    transaction_estimated_count = Chain.transaction_estimated_count()

    render(
      conn,
      "index.html",
      current_path: current_path(conn),
      transaction_estimated_count: transaction_estimated_count
    )
  end

  def show(conn, %{"id" => id}) do
    with {:ok, transaction_hash} <- Chain.string_to_transaction_hash(id),
         :ok <- Chain.check_transaction_exists(transaction_hash) do
      if Chain.transaction_has_token_transfers?(transaction_hash) do
        redirect(conn, to: transaction_token_transfer_path(conn, :index, id))
      else
        redirect(conn, to: transaction_internal_transaction_path(conn, :index, id))
      end
    else
      :error -> conn |> put_status(422) |> render("invalid.html", transaction_hash: id)
      :not_found -> conn |> put_status(404) |> render("not_found.html", transaction_hash: id)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex
<div class="card">
  <div class="card-body">
    <h1 class="card-title"><%= gettext "Input" %> </h1>
    <!-- Input -->
    <%= case @decoded_input_data do %>
    <% {:error, :contract_not_verified, candidates} -> %>
    <div class="alert alert-info">
      <%= gettext "To see accurate decoded input data, the contract must be verified." %>
      <%= case @transaction do %>
        <% %{to_address: %{hash: hash}} -> %>
          <%= gettext "Verify the contract " %><a href="<%= address_verify_contract_path(@conn, :new, hash)%>"><%= gettext "here" %></a>
        <% _ -> %>
          <%= nil %>
      <% end %>
    </div>
    <%= unless Enum.empty?(candidates) do %>
      <h3><%= gettext "Potential matches from our contract method database:" %></h3>
      <%= gettext "IMPORTANT: This information is a best guess based on similar functions from other verified contracts." %>
      <%= gettext "To have guaranteed accuracy, use the link above to verify the contract's source code." %>

      <%= for {:ok, method_id, text, mapping} <- candidates do %>
        <hr>
        <h3><%= text %>: </h3>

        <%= render(BlockScoutWeb.TransactionView, "_decoded_input_body.html", method_id: method_id, text: text, mapping: mapping) %>
      <% end %>
    <% end %>
    <% {:ok, method_id, text, mapping} -> %>
      <%= render(BlockScoutWeb.TransactionView, "_decoded_input_body.html", method_id: method_id, text: text, mapping: mapping) %>
    <% _ -> %>
        <div class="alert alert-danger">
          <%= gettext "Failed to decode input data." %>
        </div>
    <% end %>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex
<div class="table-responsive text-center">
  <table style="color: black;" summary="<%= gettext "Transaction Inputs" %>" class="table thead-light table-bordered">
  <tr>
  <td><%= gettext "Method Id" %></td>
  <td colspan="3"><code>0x<%= @method_id %></code></td>
  </tr>
  <tr>
  <td>Call</td>
  <td colspan="3"><code><%= @text %></code></td>
  </tr>
  </table>
</div>

<%= unless Enum.empty?(@mapping) do %>
  <div class="table-responsive text-center">
    <table style="color: black;" summary="<%= gettext "Transaction Inputs" %>" class="table thead-light table-bordered">
      <tr>
      <th scope="col"></th>
      <th scope="col"><%= gettext "Name" %></th>
      <th scope="col"><%= gettext "Type" %></th>
      <th scope="col"><%= gettext "Data" %></th>
      <tr>
      <%= for {name, type, value} <- @mapping do %>
        <tr>
          <th scope="row">
            <%= case BlockScoutWeb.ABIEncodedValueView.copy_text(type, value) do %>
              <% :error -> %>
                <%= nil %>
              <% copy_text -> %>
                <span
                  aria-label='<%= gettext "Copy Value" %>'
                  class="btn-copy-ico"
                  data-clipboard-text='<%= copy_text %>'
                  data-placement="top"
                  data-toggle="tooltip"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.5 32.5" width="32" height="32">
                    <path fill-rule="evenodd" d="M23.5 20.5a1 1 0 0 1-1-1v-9h-9a1 1 0 0 1 0-2h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zm-3-7v10a1 1 0 0 1-1 1h-10a1 1 0 0 1-1-1v-10a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1zm-2 1h-8v8h8v-8z"/>
                  </svg>
                </span>
            <% end %>
          </th>
          <td><%= name %></td>
          <td><%= type %></td>
          <td>
            <%= case BlockScoutWeb.ABIEncodedValueView.value_html(type, value) do %>
              <% :error -> %>
                <div class="alert alert-danger">
                  <%= gettext "Error rendering value" %>
                </div>
              <% value -> %>
                <pre class="transaction-input-text tile"><code><%= value %></code></pre>
              <% end %>
          </td>
        </tr>
      <% end %>
    </table>
   </div>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_emission_reward_tile.html.eex
<div class="tile tile-type-emission-reward fade-in" data-identifier-hash="<%= @validator.block.hash %>">
  <div class="row tile-body">
    <div class="col-md-2 d-flex flex-row flex-md-column align-items-left justify-content-start justify-content-lg-center mb-1 mb-md-0 pl-md-4">
      <span class="tile-label">
        <%= gettext("Emission Contract") %>
      </span>
      <span class="tile-status-label ml-2 ml-md-0">
        <%= gettext("Success") %>
      </span>
    </div>
    <div class="col-md-7 col-lg-8 d-flex flex-column pr-2 pr-sm-2 pr-md-0">
      <%= link(
        @validator.block.hash,
        to: block_path(BlockScoutWeb.Endpoint, :show, @validator.block.hash),
        class: "text-truncate") %>
      <span class="text-nowrap">
        <%= @emission_funds |> BlockScoutWeb.AddressView.address_partial_selector(nil, @current_address) |> BlockScoutWeb.RenderHelpers.render_partial() %>
        &rarr;
        <%= @validator |> BlockScoutWeb.AddressView.address_partial_selector(nil, @current_address) |> BlockScoutWeb.RenderHelpers.render_partial() %>
      </span>
      <span class="d-flex flex-md-row flex-column mt-3 mt-md-0">
        <span class="tile-title">
          <%= format_wei_value(@emission_funds.reward, :ether) %>
        </span>
      </span>
    </div>
    <div class="col-md-3 col-lg-2 d-flex flex-row flex-md-column flex-nowrap justify-content-start text-md-right mt-3 mt-md-0">
      <span class="mr-2 mr-md-0 order-1">
        <%= @validator |> block_number() |> BlockScoutWeb.RenderHelpers.render_partial() %>
      </span>
      <span class="mr-2 mr-md-0 order-2" data-from-now="<%= block_timestamp(@validator) %>"></span>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_link.html.eex
<%= link(@transaction_hash,
    to: transaction_path(BlockScoutWeb.Endpoint, :show, @transaction_hash),
    "data-test": "transaction_hash_link",
    class: "text-truncate") %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_metatags.html.eex
<%= if assigns[:transaction] do %>
  <title>
    <%= gettext(
          "Transaction %{transaction} - %{subnetwork} Explorer",
          transaction: to_string(@transaction.hash),
          subnetwork: BlockScoutWeb.LayoutView.subnetwork_title()
        ) %>
  </title>

  <meta name="description" content="<%= gettext "View transaction %{transaction} on %{subnetwork}", transaction: to_string(@transaction.hash), subnetwork: BlockScoutWeb.LayoutView.subnetwork_title() %>">
  <meta name="keywords" content="<%= gettext "Transaction %{transaction}, %{subnetwork} %{transaction}", transaction: to_string(@transaction.hash), subnetwork: BlockScoutWeb.LayoutView.subnetwork_title() %>">
<% else %>
  <%= BlockScoutWeb.LayoutView.render("_default_title.html") %>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
<% status = BlockScoutWeb.TransactionView.transaction_status(@transaction) %>
<div class="tile tile-type-<%= BlockScoutWeb.TransactionView.type_suffix(@transaction) %> fade-in" data-test="<%= BlockScoutWeb.TransactionView.type_suffix(@transaction) %>" data-identifier-hash="<%= @transaction.hash %>">
  <div class="row" data-test="chain_transaction">
    <div class="col-md-2 d-flex flex-row flex-md-column align-items-left justify-content-start justify-content-lg-center mb-1 mb-md-0 pl-md-4">
      <span class="tile-label" data-test="transaction_type"> <%= BlockScoutWeb.TransactionView.transaction_display_type(@transaction) %></span>
      <div class="tile-status-label ml-2 ml-md-0" data-test="transaction_status"><%= BlockScoutWeb.TransactionView.formatted_status(status) %></div>
    </div>
    <div class="col-md-7 col-lg-8 d-flex flex-column pr-2 pr-sm-2 pr-md-0">
      <%= render BlockScoutWeb.TransactionView, "_link.html", transaction_hash: @transaction.hash %>
      <span class="text-nowrap">
        <%= render BlockScoutWeb.AddressView, "_link.html", address: @transaction.from_address, contract: BlockScoutWeb.AddressView.contract?(@transaction.from_address) %>
        &rarr;
        <%= if @transaction.to_address_hash do %>
          <%= render BlockScoutWeb.AddressView, "_link.html", address: @transaction.to_address, contract: BlockScoutWeb.AddressView.contract?(@transaction.to_address) %>
        <% else %>
          <%= gettext("Contract Address Pending") %>
        <% end %>
      </span>
      <span class="d-flex flex-md-row flex-column mt-3 mt-md-0">
        <span class="tile-title"><%= BlockScoutWeb.TransactionView.value(@transaction, include_label: false) %> <%= gettext "Ether" %></span>
        <span class="ml-0 ml-md-1 text-nowrap"> <%= BlockScoutWeb.TransactionView.formatted_fee(@transaction, denomination: :ether, include_label: false) %> <%= gettext "TX Fee" %></span>
      </span>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex
<div class="card-tabs js-card-tabs">
  <%= if @show_token_transfers do %>
    <%= link(
          gettext("Token Transfers"),
          class: "card-tab #{tab_status("token_transfers", @conn.request_path)}",
          to: transaction_token_transfer_path(@conn, :index, @transaction)
        )
      %>
  <% end %>
  <%= link(
        gettext("Internal Transactions"),
        class: "card-tab #{tab_status("internal_transactions", @conn.request_path)}",
        to: transaction_internal_transaction_path(@conn, :index, @transaction)
      )
    %>
  <%= link(
        gettext("Logs"),
        class: "card-tab #{tab_status("logs", @conn.request_path)}",
        to: transaction_log_path(@conn, :index, @transaction),
        "data-test": "transaction_logs_link"
      )
    %>
  <%= link(
      gettext("Raw Trace"),
      class: "card-tab #{tab_status("raw_trace", @conn.request_path)}",
      to: transaction_raw_trace_path(@conn, :index, @transaction)
      ) %>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
<div class="text-nowrap row mt-3 mt-sm-0" data-test="token_transfer">
  <span class="col-xs-12 col-lg-5">
    <%= if from_or_to_address?(@token_transfer, @address) do %>
      <%= if @token_transfer.from_address_hash == @address.hash do %>
        <span data-test="transaction_type" class="text-danger">
            &#8627;
        </span>
      <% else %>
        <span data-test="transaction_type" class="text-success">
            &#8627;
        </span>
      <% end %>
    <% end %>
    <span class="d-inline-block tile-type-token-transfer-short-name">
    <%= @token_transfer |> BlockScoutWeb.AddressView.address_partial_selector(:from, @address, true) |> BlockScoutWeb.RenderHelpers.render_partial() %>
    </span>
    &rarr;
    <span class="d-inline-block tile-type-token-transfer-short-name">
    <%= @token_transfer |> BlockScoutWeb.AddressView.address_partial_selector(:to, @address, true) |> BlockScoutWeb.RenderHelpers.render_partial() %>
    </span>
  </span>
  <span class="col-xs-12 col-lg-4 ml-3 ml-sm-0 text-truncate">
  <%= token_transfer_amount(@token_transfer) %> <%= link(token_symbol(@token_transfer.token), to: token_path(BlockScoutWeb.Endpoint, :show, @token_transfer.token.contract_address_hash)) %>
  </span>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/invalid.html.eex
<section class="container">
  <div class="row">
    <div class="col-12"> 
      <div class="card">
        <div class="card-body">
          <h1 class="card-title"><%= gettext "Invalid Transaction Hash" %></h1>
          <div class="tile tile-muted text-center">
            <span> <span class="font-weight-bold"><%= @transaction_hash %></span> <%= gettext "is not a valid transaction hash" %> </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>